action: 
  start: "[Action]"
  end: "[\\Action]"

timeseries_id: 
  start: "[TimeseriesID]"
  end: "[\\TimeseriesID]"

question:
  start: "[Question]"
  end: "[\\Question]"

timeseries:
  start: "[Timeseries]"
  end: "[\\Timeseries]"

answer:
  start: "[Answer]"
  end: "[\\Answer]"

explanation:
  start: "[Explanation]"
  end: "[\\Explanation]"


