action: 
  start: "<ACTION>"
  end: "<\\ACTION>"

timeseries_id: 
  start: "<TIMESERIES>"
  end: "<\\TIMESERIES>"

question:
  start: "<QUESTION>"
  end: "<\\QUESTION>"

timeseries:
  start: "<TIMESERIES>"
  end: "<\\TIMESERIES>"

answer:
  start: "<ANSWER>"
  end: "<\\ANSWER>"

explanation:
  start: "<EXPLANATION>"
  end: "<\\EXPLANATION>"


