prompts:
  - timeseries: 9,8,10,11
    question: Is the person waving before dancing?
    description: example_query
    answer: 1
  - timeseries: 9,8,10,11
    question: Is the person playing guitar at timestep 11.12?
    answer: 1
    description: example_query_fraction
  - timeseries: 2,8,4,2
    question: Is the first and last action the same?
    answer: 1
    description: example_query_comparison
