prompts:
  - timeseries: 8,12,8,12
    question: Is it correct that the person is dancing as often as they are kicking a ball?
    description: cot_comparison_count
    answer: |
      Let's solve this step-by-step:
      1. We look at the timeseries enclosed in the ${tag.timeseries.start} and ${tag.timeseries.end} tags to find the actions corresponding to the timeseriesIDs.
      2. The first timeseriesID is 8, which corresponds to the action "dancing".
      3. The second timeseriesID is 12, which corresponds to the action "kicking a ball".
      4. The third timeseriesID is 8, which corresponds to the action "dancing".
      5. The fourth timeseriesID is 12, which corresponds to the action "kicking a ball".
      6. ID 8 (dancing) appears twice and ID 12 (kicking a ball), appears twice as well.
      7. 2 == 2, so the statement is correct.
      Therefore, it is correct that the person is dancing as often as they are kicking a ball.
      Thus the answer is Yes. 

    # To summarize the translation of the timeseries to actions: ["dancing", "kicking a ball", "dancing", "kicking a ball"].
  - timeseries: 8,12,8,15
    question: Are the actions performed by the person similar before and after they perform kicking a ball?
    description: cot_comparison
    answer: |
      Let's solve this step-by-step:
      1. We look at the timeseries enclosed in the ${tag.timeseries.start} and ${tag.timeseries.end} tags to find the actions corresponding to the timeseriesIDs.
      2. The first timeseriesID is 8, which corresponds to the action "dancing".
      3. The second timeseriesID is 12, which corresponds to the action "kicking a ball".
      4. The second action "kicking a ball" is the relevant action which is asked to compare with the actions before and after it. 
      5. The third timeseriesID is 8, which corresponds to the action "dancing".
      6. The action before "kicking a ball" (12) is "dancing" (8) and the action after "Kicking a ball" (12) is "dancing" (8) as well. 
      It is correct that the person is doing similar things before and after they perform kicking a ball.
      Therefore, the answer is Yes.
    # To summarize the translation of the timeseries to actions: ["dancing", "kicking a ball", "dancing", "catching a ball"].